[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
show_error_context = True
follow_imports = normal
allow_redefinition = True
namespace_packages = True
warn_unreachable = True
check_untyped_defs = True
exclude = (?x)(
    .*revenue_search_class.*    # files named "one.py"
    | .*options_parser.*  # or files ending with "two.pyi"
    | .*construction.*   # or files starting with "three."
  )

[mypy-indi.capdist.capital_distribution_functions_v1]
follow_imports = skip

[mypy-recon.income_st_construction_lib_v2]
follow_imports = skip

[mypy-htmlextr.compens.options_parcer_lib_v6]
follow_imports = skip

[mypy-htmlextr.compens.html_parse_lib_v5]
follow_imports = skip

[mypy-indi.revenue.revenue_search_class_v2]
follow_imports = skip

[mypy-h5py.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-lxml.etree.*]
ignore_missing_imports = True

[mypy-lxml.*]
ignore_missing_imports = True

[mypy-bs4.*]
ignore_missing_imports = True

[mypy-mysql.*]
ignore_missing_imports = True

[mypy-mysql.connector.*]
ignore_missing_imports = True

[mypy-mysql.connector.errors.*]
ignore_missing_imports = True

[mypy-tensorflow.*]
ignore_missing_imports = True

[mypy-tensorflow.keras.*]
ignore_missing_imports = True

[mypy-keras.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-nltk.*]
ignore_missing_imports = True

[mypy-psycopg2.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True