[project]
name = "pydb"
version = "0.1.1"
description = "MySQL and PostgreSQL access"
authors = [
    {name = "mgadmin",email = "vkugushev@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "mysql-connector-python (>=9.6.0,<10.0.0)",
    "psycopg[binary] (>=3.3.3,<4.0.0)",
    "pydantic",
    "psycopg-pool (>=3.3.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
